#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function clone_repo {
	owner=$1
	name=$2
	sha=$3

	path=$SCRIPT_DIR/examples/$name
	if [ ! -d "$path" ]; then
		echo "Cloning $owner/$name"
		git clone "https://github.com/$owner/$name" "$path"
	fi

	pushd "$path" >/dev/null
	actual_sha=$(git rev-parse HEAD)
	if [ "$actual_sha" != "$sha" ]; then
		echo "Updating $owner/$name to $sha"
		git fetch
		git reset --hard "$sha"
	fi
	popd >/dev/null
}

clone_repo cue-lang cue 820e1530e9ff433c4a001fb61e4c48499f0bded2

find $SCRIPT_DIR/examples -type f -name '*.cue' \
    | grep -vFf $SCRIPT_DIR/known_failures.txt \
    | xargs tree-sitter parse -q -s
